### ISSUE TITLE
Onderzoek 'Google Translate op utrecht.nl' toevoegen bij gebruikersonderzoek.

### ISSUE THREAD

**Issue by JeroenduC** [nl-design-system/gebruikersonderzoek#38]
We hebben een kwantitatief onderzoek om toe te voegen bij het gebruikersonderzoek over het gebruik van Google Translate op utrecht.nl.

Bijbehorende bestanden toegevoegd aan issue.

[GoogleTranslations.xlsx](https://github.com/nl-design-system/gebruikersonderzoek/files/11259333/GoogleTranslations.xlsx)

**Comment by JeroenduC** [comment]
Onderzoek toegevoegd.

**Comment by Rozerinay** [comment]
Link naar onderzoek: https://gebruikersonderzoeken.nl/docs/onderzoek-bekijken/website-gebruik/utrecht-google-translate/
